package compiler

import (
	"fmt"

	"github.com/danfragoso/milho/mir"
)

var llvm_header = `
@memes = global i32 1

define i32 @main() {
	%1 = load i32, i32* @memes
	%2 = add i32 %1, 1
	store i32 %2, i32* @memes
	ret i32* @memes
}
`

type llvm_instruction interface {
	String() string
}

func TranspileLLVM(expr mir.Expression) string {
	fmt.Println(";Generated by the milho compiler")
	return llvm_header //+ expr.Value()
}

func llvm_transpileExpr(expr mir.Expression) string {
	switch expr.Type() {
	case mir.ListExpr:
		return llvm_transpileListExpr(expr).String()
	}

	return "call void @llvm.donothing()"
}

func llvm_transpileListExpr(expr mir.Expression) llvm_instruction {
	expressions := expr.(*mir.ListExpression).Expressions
	if len(expressions) == 0 {
		return &JSValue_Undefined{}
	}

	firstExpr := expressions[0]
	switch firstExpr.Type() {
	case mir.SymbolExpr:
		sym := firstExpr.(*mir.SymbolExpression)
		return matchListSymbolExpr(sym, expressions[1:])
	}

	return &JSValue_String{}
}
